# Generated by Django 3.2.5 on 2021-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0004_auto_20210814_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
