# Generated by Django 3.2.5 on 2021-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0006_auto_20210816_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
