# Generated by Django 3.2.6 on 2021-08-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0010_merge_20210828_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementvalue',
            name='config',
        ),
    ]
