# Generated by Django 3.2.5 on 2021-08-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Momento da medição')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('dangerUpAlarm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dangerDownAlarm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('warningUpAlarm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('warningDownAlarm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smhapp.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementVaue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smhapp.measurement')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='deviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smhapp.room'),
        ),
    ]
