# Generated by Django 3.2.5 on 2021-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0005_alter_devicetype_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
