# Generated by Django 3.2.5 on 2021-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0008_rename_measurementvaue_measurementvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
