# Generated by Django 3.2.4 on 2021-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0008_rename_measurementvaue_measurementvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementvalue',
            name='config',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
