# Generated by Django 3.2.4 on 2021-08-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smhapp', '0009_auto_20210823_1443'),
        ('smhapp', '0009_measurementvalue_config'),
    ]

    operations = [
    ]
